[package]
name = "rust_bits"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = "abort"    # Los kernels no saben qué hacer con un pánico complejo
lto = true         # Optimización total para que el archivo sea pequeño